# @format

name: deploy pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "hola mundo "
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependecies
        run: npm install
      - name: run linter
        run: npm run lint
